# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



# Кстати я хз насколько ты знаком с PyQt6. Но я сгенерировал тебе дизайн для твоей программы.
# Ты можешь открыть его в Qt Designer и настроить по своему вкусу.
# Но если ты хочешь использовать его в коде, то тебе нужно будет импортировать его и создать экземпляр класса, который там описан.
#--@miroku312

import sys
from PyQt6.QtWidgets import QApplication, QMainWindow
from PyQt6 import uic
from PyQt6.QtCore import Qt

# Наши библиотеки также если хочешь можешь сюда накидать свои библиотеки для работы с данными или что-то ещё.

class ParallaxApp(QMainWindow):
    def __init__(self):
        super().__init__()


        try:
            uic.loadUi("design.ui", self)   # Вот тут наш дизйн если что можешь настроить его в Qt Designer
        except FileNotFoundError:
            print("Error: Could not find 'design.ui'. Please create the XML file first.")
            sys.exit()


        self.parallax_strength = 20  


        self.setMouseTracking(True)
        self.centralwidget.setMouseTracking(True)


    def mouseMoveEvent(self, event):
        """
        Overrides the default mouse event to calculate offset
        and move the background layer.
        """

        width = self.width()
        height = self.height()

        mouse_x = event.position().x()
        mouse_y = event.position().y()

        offset_x = -1 * (mouse_x - width / 2) / width * self.parallax_strength
        offset_y = -1 * (mouse_y - height / 2) / height * self.parallax_strength

        new_x = -50 + offset_x
        new_y = -50 + offset_y

        self.backgroundLabel.move(int(new_x), int(new_y))


        super().mouseMoveEvent(event)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = ParallaxApp()
    window.show()
    sys.exit(app.exec())